{{ $namespace := .Release.Name }}

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ print $namespace "-web" }}
  name: {{ print $namespace "-web" }}
spec:
  ports:
  - name: 5051-5051
    port: 5051
    protocol: TCP
    targetPort: 5051
  selector:
    app: {{ print $namespace "-web" }}
  type: ClusterIP
status:
  loadBalancer: {}
